name: cookbook-dev
channels:
  - conda-forge
dependencies:
  - jupyter-book
  - jupyterlab
  - jupyter_server
  - sphinx-pythia-theme
  - arm_pyart
  - cartopy
  - matplotlib
  - numpy
  - pyrad_arm
  - wradlib
  - xarray
  - xradar
