name: trigger-book-build
on:
  pull_request:

jobs:
  build:
    # uses: ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml@main
    uses: ./.github/workflows/build-book-pullrequest.yaml
    with:
      environment_name: cookbook-dev
      environment_file: environment.yml
      path_to_notebooks: ./
      use_cached_environment: 'false'
      # artifact_name: book-zip-${{ github.event.number }}
      # Other input options are possible, see ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml
